Repository graasp/graasp-translations, pull requests merged in 2022-11, with the labels that each got.

#57 chore: add release-please
  .github/workflows/release-please.yml
Labels: chore

#61 feat: add library tree modal translations
  README.md
  src/constants/library.ts
  src/langs/de/library.json
  src/langs/en/library.json
  src/langs/fr/library.json
Labels: feature

#66 fix: export association constants
  src/constants/index.ts
Labels: bug

#73 feat: add resizable translations
  src/constants/builder.ts
  src/langs/en/builder.json
  src/langs/fr/builder.json
Labels: feature

#76 chore: add author and contributors
  package.json
Labels: chore
