Repository graasp/graasp-translations, pull requests merged in 2022-12, with the labels that each got.

#78 fix: logout should be 'abmelden' in german
  src/langs/de/builder.json
Labels: bug

#81 fix: release workflow with new composite npm publish
  .github/workflows/release-please.yml
Labels: chore

#83 feat: add publish visibility information
  src/constants/builder.ts
  src/langs/de/builder.json
  src/langs/en/builder.json
  src/langs/fr/builder.json
Labels: feature

#86 fix: rename recycle into trash and add missing translations
  src/langs/de/builder.json
  src/langs/de/messages.json
  src/langs/en/messages.json
  src/langs/fr/messages.json
Labels: bug

#88 fix: update german translations of publishing flow
  src/langs/de/builder.json
  src/langs/de/categories.json
  src/langs/de/common.json
  src/langs/en/builder.json
  src/langs/en/common.json
  src/langs/fr/builder.json
  src/langs/fr/common.json
Labels: bug, feature
