Repository graasp/graasp-translations, pull requests merged in 2024-11, with the labels that each got.

#565 chore(main): release 1.41.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#566 fix: add spanish in bundle
  src/i18n.ts
Labels: bug

#567 fix: add options
  src/i18n.ts
Labels: chore

#568 chore(main): release 1.42.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending
