Repository graasp/graasp-translations, pull requests merged in 2024-06, with the labels that each got.

#427 fix(build): create a commonJs bundle
  .eslintignore
  .gitignore
  package.json
  src/i18n.ts
  src/index.ts
  tsconfig.cjs.json
  tsconfig.esm.json
  tsconfig.json
  yarn.lock
Labels: build, chore

#431 fix: update release-please
  .github/workflows/release-please.yml
Labels: chore

#437 chore(main): release 1.30.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#447 chore(main): release 1.30.1
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#448 chore(main): release 1.30.2
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#449 revert: removal of default export
  src/index.ts
Labels: chore

#450 chore(main): release 1.30.3
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#453 chore(main): release 1.31.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending
